---
title: "Almond_ClassTreeAssign"
author: "Ryan Almond"
date: "2/10/2022"
output: word_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)
library(rpart) #for classification trees
library(rpart.plot) #plotting trees
library(RColorBrewer) #better visualization of classification trees
library(rattle) #better visualization of classification trees
library(caret) #for easy confusion matrix creation 
```

```{r}
heart <- read_csv("heart_disease-1.csv")
```

```{r}
heart = heart %>% mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = fct_recode(HeartDisease,"No" = "0", "Yes" = "1")) %>%
  mutate(Sex = as_factor(Sex)) %>% 
  mutate(ChestPainType = as_factor(ChestPainType)) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina))
  
#str(heart)
#summary(heart)
```

```{r}
set.seed(12345) 
heart_split = initial_split(heart, prop = 0.7, strata = HeartDisease) #70% in training
train = training(heart_split) 
test = testing(heart_split)
```

```{r}
heart_recipe = recipe(HeartDisease  ~., train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)
```


```{r}
#extract the tree's fit from the fit object
tree = heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

#plot the tree
fancyRpartPlot(tree)
```

```{r}
heart_fit$fit$fit$fit$cptable
```
The optimal value is 0.0100 with 6 splits and xerror of .3379791.  


```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```


```{r}
heart_recipe = recipe(HeartDisease ~., train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                          levels = 25) #try 25 sensible values for cp

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

tree_res = 
  heart_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```
```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```

The best value is 0.0422.  

```{r}
final_wf = 
  heart_wflow %>% 
  finalize_workflow(best_tree)
```

```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree) 

```

```{r}
treepred = predict(final_fit, train, type = "class")
head(treepred)
```

```{r}
confusionMatrix(treepred$.pred_class,train$HeartDisease,positive="Yes") 
```

We got an accuracy of 0.8396 on the training set for the heart data set.

```{r}
treepred_test = predict(final_fit, test, type = "class")
head(treepred_test)
```


```{r}
confusionMatrix(treepred_test$.pred_class,test$HeartDisease,positive="Yes") #predictions first then actual
```
We got an accuracy of 0.8261 on the testing set for the heart data set.  

```{r}
blood <- read_csv("Blood.csv")
```
```{r}
blood = blood %>% mutate(DonatedMarch = as_factor(DonatedMarch)) %>%
  mutate(DonatedMarch = fct_recode(DonatedMarch,"No" = "0", "Yes" = "1"))
```


```{r}
set.seed(1234) 
blood_split = initial_split(blood, prop = 0.7, strata = DonatedMarch) #70% in training
train2 = training(blood_split) 
test2 = testing(blood_split)
```

```{r}
set.seed(1234)
folds = vfold_cv(train2, v = 5)
```

```{r}
blood_recipe = recipe(DonatedMarch ~., train2) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                          levels = 25) #try 25 sensible values for cp
blood_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(blood_recipe)

tree_res = 
  blood_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```
```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```

```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```
The optimal value appears to be 0.0178.  

```{r}
final_wf = 
  blood_wflow %>% 
  finalize_workflow(best_tree)
```

```{r}
final_fit = fit(final_wf, train2)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree) 
```


```{r}
treepred = predict(final_fit, train2, type = "class")
head(treepred)
```

```{r}
confusionMatrix(treepred$.pred_class,train2$DonatedMarch,positive="Yes") #predictions first then actual
```

0.8069 is the accuracy on the train set for the blood data set.  

```{r}
treepred_test = predict(final_fit, test2, type = "class")
head(treepred_test)
```

```{r}
confusionMatrix(treepred_test$.pred_class,test2$DonatedMarch,positive="Yes") #predictions first then actual
```

0.7822 is the accuracy on the test set for the blood data set.  